name: my-CI-CD

on:
  workflow_dispatch:
    inputs:
      environments:
        description: Below are the avaiable environment
        default: dev
        type: choice
        options:
          - dev
          - main
jobs: 
  code:
    runs-on: ubuntu-latest
    steps:
      - name: This is code stage
        run: echo "Code in progress"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: This is build stage
        run: echo "This is Build stage"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: This is Test stage
        run: echo "This is Test stage"
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: This is Deploy stage
        run: echo "This is deploy stage"
  
