name: test
on: 
  push: 
    branches:
      - main

jobs: 
  greeting:  
    runs-on: ubuntu-latest
    steps: 
      - name: Greet the user
        run: echo "Hello world!"
      - name: Say bye
        run: echo "Goodbye!! ${USER}"




    