name: Multi-job

on: 
    push:
        branches: [ main ]
# workflow level env vars p3
env:
    APP_NAME: myapp

jobs:
    build:
        runs-on: ubuntu-latest
        # job level env vars p2
        env: 
            ENVIRONMENT: staging

        steps:
            # step level env vars p1
            - name: Print Message of Build and env vars
              env:
                VERSION: "1.1.0"
              run: |
                echo "Building the APP"
                echo "Application $APP_NAME"
                echo "Environment $ENVIRONMENT"
                echo "Version info $VERSION"
            - name: Print the commit SHA and actor
              run: |
                echo "commit ID ${{ github.SHA }}"
                echo "Actor name is ${{ github.ref_name }}"

    test:
        runs-on: ubuntu-latest
        outputs:
            date: ${steps.date.outputs.date} 

        steps:
            - name: Print Message of Test
              run: echo "Running the TEST"
            - name: Setting the output
              run: echo " date=$(date)"  >> $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Print Message of Deployment
              run: echo " Deploying"
            - name: Get the output from test job and print here
              run: echo "Output from test ${{ needs.test.outputs.date }}"

