# This is a PR check file.
# This file will trigger on Pull request to pr-cycle branch for learning purpose
# Perform the file size check and display the file size || get fail if file size is greater than 1 MB

# Later will add few more options like:
# Read the branch name from
# Fail if it doesn't follow the pattern feature, fix or docs

# One for job
# This job will check the PR body
# Read the PR body 
# Warn (but doesn't fail) if the PR description is empty


name: PR-check

on: 
    pull_request:
        branches: [ pr-cycle ]

jobs:
    PR-check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4

            - name: Checking the file size
              run: |
                echo "Running the file size check"

                for file in $(find . -type f);
                do
                  size=$(du -k "$file" | cut -f1)
                  if [ $size -gt 1024 ];
                  then 
                    echo "File is larger than 1 MB"
                    exit 1
                  fi
                done
                echo "All files are under 1 MB"

    branch-name-check:
        runs-on: ubuntu-latest
        steps:
            - name: Get the Branch name
              run: |
                echo "We can print the branch name in two ways"
                echo "By giving the full path is-  ${{ github.event.pull_request.head.ref }}"
                echo "Second method for branch name is-  ${{ github.head_ref }}"
                
                # Adding for pr-cycle branch name for testing purpose
                # Add if compare the base or target branch only then is working 
                echo "${{ github.event.pull_request.base.ref }}" | grep -E '^(feature|docs|fix|pr-cycle)' 

                # For main branch is getting fail below if for main 
                # later will comment it 
                # echo "${{ github.head_ref }}" | grep -E '^(feature|docs|fix|pr-cycle)'

    pr-body-check:
        runs-on: ubuntu-latest
        steps:
            - name: Check the PR description
              run: |
                echo "PR description"
                echo "${{ github.event.pull_request.body }}"

                BODY="${{ github.event.pull_request.body }}""
                # -z checks if empty
                [ -z "$BODY" ] && echo "Warning: PR description is empty"