# this workflow will run on PR on main branch
name: pr-check

on: 
  pull_request:
    branches: [main]

jobs:
    checkpr:
        runs-on: ubuntu-latest
        steps:
            - name: PR check running for the branch
              run: echo "PR check is run for branch ${{ github.action_ref}}"

